from python
## it will check for python image in DE if not present then pull from Docker hub
maintainer harsh.mangal1108@gmail.com
## developer of docker image (optional)
run mkdir /mycode
## run instruction can execute any linux command inside my docker image that i am going to create
copy first.py /mycode/first.py
## it will copy code from local system to docker image so
cmd python /mycode/first.py
## so this will run python code as default paresnt process
