from continuumio/anaconda3:4.4.0
#it is best becuase scipy etc are present
maintainer harsh
copy ./untitled    /usr/local/python/
expose 5000
workdir /usr/local/python/
run pip install -r requirement.txt
cmd python app.py
